apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gastos-deployment
  name: gastos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gastos-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gastos-deployment
    spec:
      containers:
        - image: lucas55i/gastos-pessoais:1.0
          name: gastos-pessoais
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
              cpu: "0.25"
              memory: 128Mi
          # startupProbe: # Onde definimos a nossa probe de inicialização
          #   httpGet: # O tipo de teste que iremos executar, neste caso, iremos executar um teste HTTP
          #     path: / # O caminho que iremos testar
          #     port: 80 # A porta que iremos testar
          #   initialDelaySeconds: 10 # O tempo que iremos esperar para executar a primeira vez a probe
          #   periodSeconds: 10 # De quanto em quanto tempo iremos executar a probe
          #   timeoutSeconds: 5 # O tempo que iremos esperar para considerar que a probe falhou
          #   successThreshold: 1 # O número de vezes que a probe precisa passar para considerar que o container está pronto
          #   failureThreshold: 3 # O número de vezes que a probe precisa falhar para considerar que o container não está pronto
