---
- name: Ansible Prompt | Creating user on Linux
  hosts: debian01
  vars_prompt: 
    - name: username
      prompt: Qual e o seu username?
      private: false
    - name: password
      prompt: Qual é a sua senha?
      private: true # Opcional - default = true
      encrypt: "md5_crypt" # Required passlib
      confirm: yes
      salt_size: 8
    - name: shell
      prompt: Qual é o seu Shell?
      private: false
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Usuário: {{ username }} | Password: {{ password }} | Shell: {{ shell }}"
    - name: USER | Add user
      ansible.builtin.user:
        name: "{{username}}"
        comment: "User create by Ansible"
        shell: "{{shell}}"
        home: "/home/{{username}}"
        password: "{{password}}"

...
