---
- name: Ansible Register Filters
  hosts: debian01
  tasks:
    - name: SISOP | Find files
      ansible.builtin.find:
        path: /home/lucas/LUCAS-PROFETA
        patterns: "*.cfg"
      register: output

    - name: SISOP | Show files
      ansible.builtin.debug:
        msg: "{{ output.files | map(attribute='path') | last }}"
...
