---
- name: Ansible Handlers
  hosts: debian01
  tasks:
    - name: NGINX | Change Listerner
      ansible.builtin.replace:
        dest: /etc/nginx/nginx.conf
        regex: 'listen            80 default_server;'
        replace: 'listen      {{ansible_default_ipv4.address }}:80 default_server;'
      notify: Restart Nginx
  handlers:
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
...
